### ISSUE TITLE
Doesn't work with Gleam >= 0.32

### ISSUE THREAD

**Issue by bentomas** [bcpeinhardt/glance_printer#1]
I tried running `gleam fix` but that didn't seem to do the trick.

**Comment by bcpeinhardt** [comment]
Will take a look in the next day or two :) If glance is up to date with 0.32 I'll want to update glance printer to reflect that.

**Comment by bcpeinhardt** [comment]
I just published v1 which should work for gleam >= 0.32.0 :)
